# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('friend_type', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KnownMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('say', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200, null=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steelframe.Friend')),
            ],
        ),
        migrations.CreateModel(
            name='StateChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='LEAVE', max_length=100)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steelframe.Friend')),
            ],
        ),
        migrations.AddField(
            model_name='eventlog',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steelframe.Friend'),
        ),
    ]
