# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('steelframe', '0002_auto_20170613_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=100)),
                ('job_command', models.CharField(max_length=200)),
                ('command_type', models.CharField(max_length=50)),
                ('command_args', models.CharField(max_length=200)),
                ('job_status', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='steelframe.Friend')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to='steelframe.Friend')),
            ],
        ),
    ]
