# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steelframe', '__first__'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='steelframe.Friend'),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to='steelframe.Friend'),
        ),
    ]
